openapi: "3.0.0"
info:
  description: "Example API"
  version: "1.0.0"
  title: "Example API"
  contact:
    email: "markel.tuzinskiy@gmail.com"
  license:
    name: "LSC"
servers:
  - url: "my.server/api"
tags:
  - name: "users"
    description: "User-related stuff"
paths:
  $ref: "users/paths.yaml"
components:
  schemas:
    User:
      $ref: "users/user.yaml"
    UserName:
      $ref: "users/name.yaml"
